### ISSUE TITLE
Open CV error

### ISSUE THREAD

**Issue by manuikhor** [takemetosiberia/ComfyUI-SAMURAI--SAM2-#1]
OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1295: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

**Comment by takemetosiberia** [comment]
Hello. Your opencv library does not support GUI. To avoid compatibility
issues, I have updated the requierements.txt file.

**Comment by manuikhor** [comment]
Thank you, still having the same issue: 

SAMURAIBoxInputNode
OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1295: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

**Comment by manuikhor** [comment]
Having a example workflow with input/output, would help a lot.

**Comment by takemetosiberia** [comment]
Please send me the result of this command:
pip list | grep opencv

**Comment by w0ver** [comment]
okay i get the same problem 

here is the command : 
got prompt
Getting box for frame 0 (refresh state: 0)
!!! Exception during processing !!! OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1295: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

Traceback (most recent call last):
  File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\samurai_nodes\samurai_node.py", line 79, in get_box
    cv2.destroyAllWindows()
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1295: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'


Prompt executed in 0.64 seconds

**Comment by manuikhor** [comment]
> pip list | grep opencv

opencv-contrib-python             4.10.0.84
opencv-contrib-python-headless    4.10.0.84
opencv-python                     4.10.0.84
opencv-python-headless            4.10.0.84

Im on windows btw

**Comment by w0ver** [comment]
> > pip list | grep opencv
> 
> opencv-contrib-python 4.10.0.84 opencv-contrib-python-headless 4.10.0.84 opencv-python 4.10.0.84 opencv-python-headless 4.10.0.84
> 
> Im on windows btw

@manuikhor 

look you had to add them into : \ComfyUI_windows_portable\python_embeded 

.\python.exe -m pip install hydra-core omegaconf loguru
.\python.exe -m pip install opencv-python>=4.5.0

i did those 2 and it did work and the nodes show in comfy 
but just get new error with the refiner node 


im on windows too

**Comment by manuikhor** [comment]
Hey @w0ver I am using de CLI version of Comfy, so I should add them into the venv. It still not working. Sadly.

**Comment by planb788** [comment]
Try to open a CMD terminal in the directory where python.exe is located, then enter 
`python -m pip uninstall opencv-python-headless`, followed by `python -m pip install opencv-python -U`. If you find that the current version is already up-to-date when using `python -m pip install opencv-python -U`, then first use `python -m pip uninstall opencv-python` to uninstall the current opencv-python. As for why you also need to uninstall opencv-python-headless earlier, it's because this library might be preventing the GUI interface from popping up.
