### ISSUE TITLE
"SAM2Base.init() got an unexpected keyword argument 'no_obj_embed_spatial'"

### ISSUE THREAD

**Issue by w0ver** [takemetosiberia/ComfyUI-SAMURAI--SAM2-#2]
**when running the nodes everything work fine but when it come to the refine node i get this error :**
"SAM2Base.init() got an unexpected keyword argument 'no_obj_embed_spatial'"
here is the command :

got prompt
Getting box for frame 0 (refresh state: 0)
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
SAMURAI mode: True
!!! Exception during processing !!! Error in call to target 'sam2.sam2_video_predictor.SAM2VideoPredictor':
TypeError("SAM2Base.init() got an unexpected keyword argument 'no_obj_embed_spatial'")
full_key: model
Traceback (most recent call last):
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\hydra_internal\instantiate_instantiate2.py", line 92, in _call_target
return target(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SAM2\sam2\sam2_video_predictor.py", line 32, in init
super().init(**kwargs)
TypeError: SAM2Base.init() got an unexpected keyword argument 'no_obj_embed_spatial'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\samurai_nodes\samurai_node.py", line 296, in segment
self.load_model(model_name)
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\samurai_nodes\samurai_node.py", line 288, in load_model
self.predictor = build_sam2_video_predictor(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SAM2\sam2\build_sam.py", line 71, in build_sam2_video_predictor
model = instantiate(cfg.model, recursive=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\hydra_internal\instantiate_instantiate2.py", line 226, in instantiate
return instantiate_node(
^^^^^^^^^^^^^^^^^
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\hydra_internal\instantiate_instantiate2.py", line 347, in instantiate_node
return _call_target(target, partial, args, kwargs, full_key)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\hydra_internal\instantiate_instantiate2.py", line 97, in _call_target
raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'sam2.sam2_video_predictor.SAM2VideoPredictor':
TypeError("SAM2Base.init() got an unexpected keyword argument 'no_obj_embed_spatial'")
full_key: model

**Comment by em0xi0nx** [comment]
have you found the solution for this?

**Comment by w0ver** [comment]
i didn't sadly, i think the project is abandoned
